### ISSUE TITLE
This is not working anymore ...

### ISSUE THREAD

**Issue by k0tkin** [ziplokk1/incapsula-cracker#6]
Hi,

I'm trying to use it against https:// offerupnow dot com but no success
2 question:

1- "{scheme}://{host}/_IncapsulaResource" shouldn't be "{scheme}://{host}/_Incapsula_Resource" ?

2- When you got blocked how you get access to "_Incapsula_Resource?SWKMTFSR" ? this resource is blocked and is not accessible

**Comment by alfonsogacevedo** [comment]
Yeah, this does not seem to be working for me either. I tried using the hotfix branch and even made some changes internally that were not working (replaced _IncapsulaResource references with _Incapsula_Resource and a change here https://github.com/ziplokk1/incapsula-cracker/blob/hotfix/incapsula/requests_.py#L20 since it returns only one array thus was breaking)

This is still not working. Is anybody able to get this to work?

**Comment by ziplokk1** [comment]
I'm no longer maintaining this version. Please see [here](https://github.com/ziplokk1/incapsula-cracker-py3) for an updated version which is compatible with python3. It works with your link that you provided.

Thank you.
